language: python
# TODO: https://docs.travis-ci.com/user/multi-os/
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
  - "pypy"
  - "pypy3"
script: nosetests
sudo: false
matrix:
    allow_failures:
        - python: nightly
