sudo: false
language: python
matrix:
    include:
      - python: "2.7"
      - python: "3.3"
      - python: "3.4"
      - python: "3.5"
      - python: "nightly"
      - python: "pypy"
      - python: "pypy3"
      - os: osx
        language: generic
    allow_failures:
      - python: "nightly"
before_install:
  # Test using the Apple-provided Python since it'll be most likely to fail
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo easy_install pip; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo pip install nose mock coverage; fi
install:
  - pip install coveralls
script: nosetests
after_success: coveralls
