language: python
# TODO: https://docs.travis-ci.com/user/multi-os/
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
  - "pypy"
  - "pypy3"
install:
  - pip install coveralls
script: nosetests
after_success: coveralls
sudo: false
matrix:
    allow_failures:
        - python: 3.2      # Broke when I added coverage
        - python: nightly
